### ISSUE TITLE
phoenixdb can't connect  hbase

### ISSUE THREAD

**Issue by zhenghan008** [lalinsky/python-phoenixdb#8]
hi, all!
I have a problem to solve.I encountered an error when I used phoenixdb.I have opened the queryserver service.
my code:
import phoenixdb
database_url = 'http://3.9.8.130:8765/'
conn = phoenixdb.connect(database_url, autocommit=True)
cursor = conn.cursor()

cursor.execute('''select * from SYSTEM."TABLE"''')
print cursor.fetchall()
the error:
phoenixdb.errors.InternalError: (u'RuntimeException: java.sql.SQLException: No suitable driver found for start -> SQLException: No suitable driver found for start', None, None, None)

**Comment by lalinsky** [comment]
I'm sorry, I can't help you with this. This project has been integrated into Phoenix itself. 

Can you please ask the Phoenix devs on the mailing list?

https://phoenix.apache.org/mailing_list.html

**Comment by zhenghan008** [comment]
@lalinsky ok!thank you!
